create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  whatsapp text not null,
  email text not null,
  endereco text not null,
  servicos_realizados integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.clientes enable row level security;

create policy "Permitir leitura publica de clientes"
on public.clientes
for select
to anon
using (true);

create policy "Permitir cadastro publico de clientes"
on public.clientes
for insert
to anon
with check (true);

create policy "Permitir edicao publica de clientes"
on public.clientes
for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de clientes"
on public.clientes
for delete
to anon
using (true);
